param([switch]$Resume)
$ErrorActionPreference="Stop";$repo="C:\Users\jiheo\tca_map";$dir=Join-Path $repo "reports\epoch9e_mechanics_smoke";$monitor=Join-Path $dir "host_resource_monitor.json";$stdout=Join-Path $dir "runner_stdout.log";$stderr=Join-Path $dir "runner_stderr.log";$result=Join-Path $dir "result.json";$ceiling=82.0
if(Test-Path -LiteralPath $monitor){throw "Refusing to overwrite monitor"};if((Test-Path -LiteralPath $result)-and-not $Resume){throw "Use -Resume for existing result"};New-Item -ItemType Directory -Path $dir -Force|Out-Null
$existing=& wsl.exe -e bash -lc "pgrep -af '[r]un_epoch9e_mechanics_smoke.py' || true";if($existing){throw "An Epoch 9E mechanics worker is already active: $existing"}
function Sample{$os=Get-CimInstance Win32_OperatingSystem;$t=[int64]$os.TotalVisibleMemorySize*1024;$f=[int64]$os.FreePhysicalMemory*1024;$u=$t-$f;$g=0.0;try{$x=& nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits 2>$null;if($LASTEXITCODE-eq 0-and$x){$g=[double](($x|%{[double]$_.Trim()}|Measure-Object -Sum).Sum)}}catch{};[pscustomobject]@{used=$u;percent=100.0*$u/$t;gpu=$g}}
$resumeArg=if($Resume){" --resume"}else{""};$cmd="set -e; cd /mnt/c/Users/jiheo/tca_map; export MUJOCO_GL=egl; export PYTHONUNBUFFERED=1; exec /home/jiheon/miniconda3-official/envs/official-smolvla-libero/bin/python scripts/run_epoch9e_mechanics_smoke.py$resumeArg";$args="-e bash -lc `"$cmd`"";$base=Sample;$peak=$base;$gpu=$base.gpu;$breach=$false;$start=Get-Date -Format o;$p=Start-Process wsl.exe -ArgumentList $args -PassThru -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr
while(-not$p.HasExited){Start-Sleep 1;$p.Refresh();$s=Sample;if($s.used-gt$peak.used){$peak=$s};if($s.gpu-gt$gpu){$gpu=$s.gpu};if($s.percent-ge$ceiling){$breach=$true;$kill='pids=$(pgrep -f ''^/home/jiheon/miniconda3-official/envs/official-smolvla-libero/bin/python scripts/run_epoch9e_mechanics_smoke.py'' || true); if [ -n "$pids" ]; then kill -TERM $pids; fi';& wsl.exe -e bash -lc $kill|Out-Null;break}}
$p.WaitForExit();$final=Sample;$o=[ordered]@{schema_version="epoch9e.mechanics_smoke_host_resource.v1";started_at=$start;completed_at=(Get-Date -Format o);command=$cmd;resume=[bool]$Resume;runner_exit_code=[int]$p.ExitCode;baseline_host_ram_percent=[double]$base.percent;peak_host_ram_percent=[double]$peak.percent;final_host_ram_percent=[double]$final.percent;peak_host_used_physical_bytes=[int64]$peak.used;baseline_gpu_used_mib=[double]$base.gpu;peak_gpu_used_mib=[double]$gpu;final_gpu_used_mib=[double]$final.gpu;host_ram_ceiling_percent=$ceiling;host_ram_ceiling_breached=$breach;scientific_result_path="reports/epoch9e_mechanics_smoke/result.json";scientific_result_sha256_after_runner=if(Test-Path $result){(Get-FileHash -Algorithm SHA256 $result).Hash}else{$null};stdout_path="reports/epoch9e_mechanics_smoke/runner_stdout.log";stdout_sha256=if(Test-Path $stdout){(Get-FileHash -Algorithm SHA256 $stdout).Hash}else{$null};stderr_path="reports/epoch9e_mechanics_smoke/runner_stderr.log";stderr_sha256=if(Test-Path $stderr){(Get-FileHash -Algorithm SHA256 $stderr).Hash}else{$null}}
$tmp="$monitor.tmp";$o|ConvertTo-Json -Depth 8|Set-Content $tmp -Encoding UTF8;Move-Item $tmp $monitor;$o|ConvertTo-Json -Depth 8;if($p.ExitCode-ne 0-or$breach){exit 1};exit 0
